# Generated by Django 5.0.6 on 2024-06-29 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('end_user', '0004_purchaseditem_purchase_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='denominationsmaster',
            name='user_paid_cash',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
