# Generated by Django 5.0.6 on 2024-06-29 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('end_user', '0006_remove_denominationsmaster_total_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingmaster',
            name='total_tax',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
